version: '3.9'
services:
    ussage:
        image: ussage
        container_name: ussage
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - '3000:3000'
        restart: always
        stdin_open: true
        tty: true